<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('42', '/uploads/allimg/180824/1-1PR4013421463.jpg');
$maNum = 1;
$myaddons[$maNum] = array('43', '/uploads/allimg/180824/1-1PR4013AR19.jpg');
$maNum = 2;
$myaddons[$maNum] = array('44', '/uploads/allimg/180824/1-1PR4013TJ04.jpg');
$maNum = 3;
$myaddons[$maNum] = array('45', '/uploads/allimg/180824/1-1PR4013912V4.jpg');
$maNum = 4;
$myaddons[$maNum] = array('46', '/uploads/allimg/180824/1-1PR4013954447.jpg');
$maNum = 5;
