<li class="mui-table-view-cell mui-media">
									<a href="[field:arcurl/]">
										<img class="mui-media-object mui-pull-left lawyer-img" src="images/lawyer.jpg">
										<div class="mui-media-body">
											<h4>[field:title/]<i></i></h4>
											<p class="mui-ellipsis">擅长：[field:skill/]</p>
                                            <p class="mui-ellipsis"><span>执业律所</span> [field:addr/]</p>
                                            <p class="mui-ellipsis renzheng">执业认证</p>
                                            <p class="mui-ellipsis">执业证号：[field:license/]</p>
										</div>
									</a>
								</li>