<?php
$z[0]=Array("arcurl","",115,130);
$z[0][4]=array();
$z[1]=Array("title","",139,153);
$z[1][4]=array();
$z[2]=Array("title","",165,179);
$z[2][4]=array();
$z[3]=Array("picname","",186,202);
$z[3][4]=array();
$z[4]=Array("arcurl","",335,350);
$z[4][4]=array();
$z[5]=Array("title","",375,389);
$z[5][4]=array();
$z[6]=Array("title","",391,405);
$z[6][4]=array();
$z[7]=Array("pubdate","",584,635);
$z[7][4]=array();
$z[7][4]['function']="MyDate('Y-m-d H:i',@me)";

?>