<li>
                            <div class="h15"></div>
                            <div class="pic fl"> <a href="[field:arcurl/]" title="[field:title/]"><img alt="[field:title/]" src="[field:picname/]"/></a></div>
                            <div class="tit_info fl">
                                <div class="title h40"><a  href="[field:arcurl/]" target="_blank" title="[field:title/]">[field:title/]</a></div>
                                <div class="info"></div>
                            </div>
                            <div class="date fr"><span class="xh_time hide">[field:pubdate function="MyDate('Y-m-d H:i',@me)"/]</span>
                                <p class="date_y"></p>
                                <p class="date_md"></p>
                            </div>
                            <div class="clear"></div>
                        </li>