<?php
$z[0]=Array("global","(@me%2=0)? @me='style=\"float:right;\"':@me='';",4,106);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("dtime","",312,361);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[2]=Array("username","",371,413);
$z[2][4]=array();
$z[2][4]['function']="cutPhone(@me)";
$z[3]=Array("msg","",447,459);
$z[3][4]=array();
$z[4]=Array("reply","",514,528);
$z[4][4]=array();

?>