<?php
$z[0]=Array("global","if(@me%2==0) {@me=\"style='float:right'\";} else {@me =\"\" ;}",4,119);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("dtime","",325,374);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[2]=Array("username","",384,426);
$z[2][4]=array();
$z[2][4]['function']="cutPhone(@me)";
$z[3]=Array("msg","",460,472);
$z[3][4]=array();
$z[4]=Array("reply","",527,541);
$z[4][4]=array();

?>