
	
<field:month itemname="月法律顾问" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:month>

<field:company itemname="年法律顾问" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:company>

<field:method itemname="中小企业特惠服务方案" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:method>
<field:body itemname="文章内容" autofield="1" notsend="0" type="textdata" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:body>