<li>
                    <div class="h15"></div>
                    <div class="tit_info fl">
                        <div class="title h40"><a href="[field:id runphp='yes'] $id=@me;@me='';$url=GetOneArchive($id);@me=$url['arcurl'];[/field:id]" target="_blank" title="[field:title/]">[field:title/]</a></div>
                        <div class="info">[field:description/]</div>
                    </div>
                    <div class="clear"></div>
                </li>