<li>
                <div>
                    <h3>最新评价</h3>
                    <p class="wx"><img src="/templets/lawyer/images/wuxing.png" alt=""></p>
                </div>
                <p><span>2018-8-10 * 用户 [field:username function="（@me=='guest' ? '游客' : @me）"/]：</span>[field:msg/]</p>
                <p><span>管理员：</span>能帮到您是最好的。祝福您万事如意。</p>
            </li>
            
        </ul> 
    <a href="/cla/6">查看更多</a> </section>
  <div class="in-brand">
    <div class="gdn-shangbiao">
      <div class="sb-inner"> </div>
      <div class="sb-inner"> </div>
      <div class="sb-inner"> </div>
      <div class="sb-inner"> </div>
      <div class="sb-inner"> </div>
      <div class="sb-inner"> </div>
      <div class="sb-inner"> </div>
      <div class="sb-inner"> </div>
      <div class="sb-inner"> </div>
      <div class="sb-inner"> </div>
    </div>
    <div class="in-brand-title"></div>
    <div class="in-brand-btns"> <a target="_blank" href="/nsht/">了解更多，点我</a> </div>
  </div>
</div>
{dede:include filename='footer.htm'