<div class="zj_bg" style="background: url('[field:picname/]') no-repeat;background-size:cover;">
                    			<div class="zj_block">
                    				<div class="zj_main">
                    					<h1><a href="[field:arcurl/]">[field:title/]</a></h1>
                    					<span>[field:tag/]</span>
                    					<p>擅长领域：[field:skill/]</p>
                    				</div>
                    			</div>
               					<div class="zj_isShow">
									<div class="zj_main">
										<h1><a href="[field:arcurl/]">[field:title/]</a></h1>
										<span>合伙人</span>
										<h3>13122839281</h3>
<!--										<p>“[field:body function='cn_substr(html2text(@me),600)'/]...<a href="[field:arcurl/]">[详情]</a>”</p>-->
										<p>“[field:id runphp='yes'] $aid = @me; $row = $GLOBALS['dsql']->GetOne("Select body From 'dede_addonarticle' where aid='$aid' "); @me = cn_substr(strip_tags("{$row['body']}"),400);[/field:id]...<a href="[field:arcurl/]">[详情]</a>”</p>
										<div class="zj_addr">
											<p class="fl"><span>半小时</span>内响应>></p>
											<p class="fr">[field:address/]</p>
										</div>
									</div>
								</div>
                    		</div>