<li>
                <div>
                    <h3>最新评价</h3>
                    <p class="wx"><img src="/templets/lawyer/images/wuxing.png" alt=""></p>
                </div>
                <p><span>[field:dtime function="MyDate('Y-m-d H:i',@me)"/] * 用户 [field:username function="cutPhone(@me)"/]：</span></p>
                <p>[field:msg function="replyMsg(@me)"/]</p>
                <p>[field:reply/]</p>
            </li>