<li>
            <h2><a href="[field:arcurl/]">[field:title/]</a></h2>
            <a href="[field:arcurl/]" class="buy">
            <p><small>￥</small>[field:trueprice/]<small>元</small></p>
            <b>查看详情</b> </a> </li>
        {/dede:proList}
    </ul>
    <div class="more">加载更多...</div>
    <!--<div class="web-page">
		<ul class="pagelist">
			{dede:pagelist listitem="info,index,end,pre,next,pageno" listsize="5"