
<field:market itemname="市场价" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:market>
<field:onetime itemname="一次(半小时)价格" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:onetime>
<field:oneday itemname="48小时内不限次价格" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:oneday>
<field:onemonth itemname="一个星期不限次" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:onemonth>

<field:monthbook itemname="包月咨询+1份文书服务" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:monthbook>
<field:body itemname="文章内容" autofield="1" notsend="0" type="textdata" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:body>
	
