<div class="zj_bg" style="background: url('[field:picname/]') no-repeat;background-size:cover;">
                    			<div class="zj_block">
                    				<div class="zj_main">
                    					<h1><a href="[field:arcurl/]">[field:title/]</a></h1>
                    					<span>[field:tag/]</span>
                    					<p>擅长领域：[field:skill/]</p>
                    				</div>
                    			</div>
               					<div class="zj_isShow">
									<div class="zj_main" url="[field:arcurl/]">
										<h1>[field:title/]</h1>
										<span>合伙人</span>
										<h3>[field:tel/]</h3>
										<p>“[field:body function='cn_substr(html2text(@me),600)'/]...[详情]”</p>
										<div class="zj_addr">
											<p class="fl"><span>半小时</span>内响应>></p>
											<p class="fr">[field:nativeplace/]</p>
										</div>
									</div>
								</div>
                    		</div>