<?php
$z[0]=Array("global","(@me%2==0)? @me='style=\"float:right;\"': @me=''",4,107);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("dtime","",313,362);
$z[1][4]=array();
$z[1][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[2]=Array("username","",372,414);
$z[2][4]=array();
$z[2][4]['function']="cutPhone(@me)";
$z[3]=Array("msg","",448,460);
$z[3][4]=array();
$z[4]=Array("reply","",515,529);
$z[4][4]=array();

?>