<?php
$z[0]=Array("feedback","\n            <li>\n                <div>\n                    <h3>最新评价</h3>\n                    <p class=\"wx\"><img src=\"/templets/lawyer/images/wuxing.png\" alt=\"\"></p>\n                </div>\n                <p><span>[field:dtime function=\"MyDate('Y-m-d H:i',@me)\"/] * 用户 [field:username function=\"cutPhone(@me)\"/]：</span></p>\n                <p>[field:msg/]</p>\n                <p><span>法易通</span>回复：[field:reply/]</p>\n            </li>\n            ",1498,2037);
$z[0][4]=array();
$z[0][4]['row']="4";
$z[0][4]['titlelen']="24";
$z[0][4]['infolen']="80";
$z[1]=Array("include","",2277,2317);
$z[1][4]=array();
$z[1][4]['file']="plus/comment.htm";

?>