<?php
$z[0]=Array("feedback","\r\n            <li>\r\n                <div>\r\n                    <h3>最新评价</h3>\r\n                    <p class=\"wx\"><img src=\"/templets/lawyer/images/wuxing.png\" alt=\"\"></p>\r\n                </div>\r\n                <p><span>[field:dtime function=\"MyDate('Y-m-d H:i',@me)\"/] * 用户 [field:username function=\"cutPhone(@me)\"/]：</span></p>\r\n                <p>[field:msg/]</p>\r\n                <p><span>法易通</span>回复：[field:reply/]</p>\r\n            </li>\r\n            ",1524,2073);
$z[0][4]=array();
$z[0][4]['row']="4";
$z[0][4]['titlelen']="24";
$z[0][4]['infolen']="80";
$z[1]=Array("include","",2317,2357);
$z[1][4]=array();
$z[1][4]['file']="plus/comment.htm";

?>