<?php
$z[0]=Array("arclist"," <a target=\"_blank\" title=\"[field:title/]\" href=\"[field:arcurl/]\" class=\"pic-item h184\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" style=\"width: 280px;height: 184px;\"><span>[field:title/]</span></a> ",27,289);
$z[0][4]=array();
$z[0][4]['flag']="p";
$z[0][4]['limit']="0,1 row='1'";
$z[1]=Array("arclist","\n              <li><i class=\"ico-law i-law184 mr10\"></i><a target=\"_blank\" href=\"[field:arcurl/]\">[[field:typename/]]</a><a target=\"_blank\" href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\n              ",343,604);
$z[1][4]=array();
$z[1][4]['row']="4";

?>