<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><div class="footer">
	<div class="login-reg">
		<a href="/member/login.php">登录 | </a>
		<a href="/member/reg_new.php">注册</a>
	</div>
	<div class="foot">
		<div class="foot-menu">
			<a href="">首页</a><a href="/joinus/">关于法易通</a><a href="/news/">法易通新闻</a><a href="/flbk/">法律百科</a>
		</div>
		<div class="foot-logo">
			<a href="/"><img src="/images/logo.png"></a>
		</div>
		<div class="foot-ico">
			<a class="ico1">律师认证</a><a class="ico2">服务保障</a><a class="ico3">法务协助</a><a class="ico4">信息安全</a>
		</div>
		<div class="zixun">
			法律咨询热线
		</div>
		<p>建议拨打时间 早上：8:00~晚上：22:00</p>
	</div>
</div>