<?php
$z[0]=Array("global","",218,243);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",500,526);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("channelartlist","\n\n                                <p><a href=\"{dede:field.typeurl/}\" class=\"lianjie\" target=\"_blank\">{dede:field.typename/}</a></p>\n\n                                ",2616,2850);
$z[2][4]=array();
$z[2][4]['typeid']="17,18,19";
$z[2][4]['row']="3";
$z[3]=Array("channelartlist","\n\n                                <p><a href=\"{dede:field.typeurl/}\" class=\"lianjie\" target=\"_blank\">{dede:field.typename/}</a></p>\n\n                                ",2921,3155);
$z[3][4]=array();
$z[3][4]['typeid']="20,21,22";
$z[3][4]['row']="3";
$z[4]=Array("channelartlist","\n\n                                <p><a href=\"{dede:field.typeurl/}\" class=\"lianjie\" target=\"_blank\">{dede:field.typename/}</a></p>\n\n                                ",3226,3460);
$z[4][4]=array();
$z[4][4]['typeid']="23,24,25";
$z[4][4]['row']="3";
$z[5]=Array("php"," echo \$solvenum['solved']; ",6598,6646);
$z[5][4]=array();

?>