<?php
$z[0]=Array("global","",305,331);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",377,407);
$z[1][4]=array();
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",446,473);
$z[2][4]=array();
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",873,909);
$z[3][4]=array();
$z[3][4]['filename']="aside.htm";
$z[4]=Array("include","",998,1035);
$z[4][4]=array();
$z[4][4]['filename']="header.htm";
$z[5]=Array("arclist","\r\n													<li class=\"mui-table-view-cell\"><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n													",5282,5442);
$z[5][4]=array();
$z[5][4]['typeid']="71";
$z[5][4]['row']="6";
$z[6]=Array("arclist","\r\n													<li class=\"mui-table-view-cell\"><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n													",5742,5902);
$z[6][4]=array();
$z[6][4]['typeid']="27";
$z[6][4]['row']="6";
$z[7]=Array("arclistsg","\r\n								<li class=\"mui-table-view-cell mui-media\">\r\n									<a href=\"[field:arcurl/]\">\r\n										<img class=\"mui-media-object mui-pull-left lawyer-img\" src=\"http://www.lawls.cn[field:picname/]\">\r\n										<div class=\"mui-media-body\">\r\n											<h4>[field:title/]<i></i></h4>\r\n											<p class=\"mui-ellipsis\">擅长：[field:skill/]</p>\r\n											<p class=\"mui-ellipsis\"><span>执业律所</span> [field:addr/]</p>\r\n											<p class=\"mui-ellipsis renzheng\">执业认证</p>\r\n											<p class=\"mui-ellipsis\">执业证号：[field:license/]</p>\r\n										</div>\r\n									</a>\r\n								</li>\r\n								",6252,6978);
$z[7][4]=array();
$z[7][4]['flag']="p";
$z[7][4]['row']="10";
$z[7][4]['addfields']="skill,addr,license";
$z[7][4]['typeid']="16";
$z[7][4]['channelid']="-8";
$z[8]=Array("include","",7468,7505);
$z[8][4]=array();
$z[8][4]['filename']="footer.htm";
$z[9]=Array("include","",7613,7652);
$z[9][4]=array();
$z[9][4]['filename']="commonJs.htm";

?>