<?php
$z[0]=Array("field","",196,218);
$z[0][4]=array();
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",219,247);
$z[1][4]=array();
$z[1][4]['name']="cfg_indexname";
$z[2]=Array("field","",287,316);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",355,413);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",829,866);
$z[4][4]=array();
$z[4][4]['filename']="header.htm";
$z[5]=Array("field","",1029,1058);
$z[5][4]=array();
$z[5][4]['name']="position";
$z[6]=Array("channel","\n                    <dd><a href=\"[field:typeurl/]\">[field:typename/]</a></dd>\n                    ",1300,1451);
$z[6][4]=array();
$z[6][4]['typeid']="60";
$z[6][4]['type']="son";
$z[7]=Array("arclist","\n        <li>\n            <h2><a href=\"[field:arcurl/]\">[field:title/]</a></h2>\n            <a href=\"[field:arcurl/]\" class=\"buy\">\n            <p><small>￥</small>[field:trueprice/]<small>元</small></p>\n            <b>查看详情</b> </a> </li>\n        ",1550,1881);
$z[7][4]=array();
$z[7][4]['addfields']="trueprice";
$z[7][4]['channelid']="6";
$z[7][4]['row']="100";
$z[8]=Array("pagelist","",1994,2065);
$z[8][4]=array();
$z[8][4]['listitem']="info,index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",4233,4270);
$z[9][4]=array();
$z[9][4]['filename']="footer.htm";

?>