<?php
$z[0]=Array("field","",305,324);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",325,353);
$z[1][4]=array();
$z[1][4]['name']="cfg_indexname";
$z[2]=Array("field","",396,425);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",467,525);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("field","",4544,4566);
$z[4][4]=array();
$z[4][4]['name']="typename";
$z[5]=Array("list","\r\n													<li class=\"mui-table-view-cell\"><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n													",4875,5023);
$z[5][4]=array();
$z[5][4]['pagesize']="15";
$z[6]=Array("pagelist","",5178,5256);
$z[6][4]=array();
$z[6][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[6][4]['listsize']="5";

?>