<?php
$z[0]=Array("field","",305,324);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",325,353);
$z[1][4]=array();
$z[1][4]['name']="cfg_indexname";
$z[2]=Array("field","",396,425);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",467,525);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("list","\r\n								<li class=\"mui-table-view-cell mui-media\">\r\n									<a href=\"[field:arcurl/]\">\r\n										<img class=\"mui-media-object mui-pull-left lawyer-img\" src=\"http://www.lawls.cn[field:picname/]\">\r\n										<div class=\"mui-media-body\">\r\n											<h4>[field:title/]<i></i></h4>\r\n											<p class=\"mui-ellipsis\">擅长：[field:skill/]</p>\r\n											<p class=\"mui-ellipsis\"><span>执业律所</span> [field:addr/]</p>\r\n											<p class=\"mui-ellipsis renzheng\">执业认证</p>\r\n											<p class=\"mui-ellipsis\">执业证号：[field:license/]</p>\r\n										</div>\r\n									</a>\r\n								</li>\r\n								",4336,5052);
$z[4][4]=array();
$z[4][4]['flag']="p";
$z[4][4]['row']="10";
$z[4][4]['addfields']="skill,addr,license";
$z[4][4]['typeid']="16";
$z[4][4]['channelid']="-8";
$z[5]=Array("pagelist","",5172,5250);
$z[5][4]=array();
$z[5][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[5][4]['listsize']="5";

?>