<?php
$z[0]=Array("global","",1288,1313);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",1565,1591);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("global","",4645,4700);
$z[2][4]=array();
$z[2][4]['name']="keyword";
$z[2][4]['function']="RemoveXSS(@me)";
$z[3]=Array("global","",5437,5492);
$z[3][4]=array();
$z[3][4]['name']="keyword";
$z[3][4]['function']="RemoveXSS(@me)";
$z[4]=Array("list","\n                    <div class=\"search-result\">\n                        <ul>\n                            <li>\n                                <p class=\"name\"> <a href=\"[field:arcurl/]\"> [field:title/] </a> </p>\n                                <p  class=\"grey2 lh25\">[field:typename/]</p>\n                                <p class=\"lh25\">[field:description/]... </p>\n                            </li>\n                        </ul>\n                    </div>\n                    ",5608,6121);
$z[4][4]=array();
$z[4][4]['perpage']="20";
$z[5]=Array("pagelist","",6244,6273);
$z[5][4]=array();
$z[5][4]['listsize']="4";
$z[6]=Array("include","",6454,6491);
$z[6][4]=array();
$z[6][4]['filename']="footer.htm";

?>